import http from './http.js'
/* eslint-disable */

export const countPartTimeTotalPeople = (o, t, p) => (http.get('/admin/home/countPartTimeTotalPeople', o, t, p))
export const countComplateTask        = (o, t, p) => (http.get('/admin/home/countComplateTask', o, t, p))
export const countTotalTask           = (o, t, p) => (http.get('/admin/home/countTotalTask', o, t, p))
export const getRecommendStats        = (o, t, p) => (http.post('/admin/report/getRecommendStats', o, t, p))
export const getRewardStats           = (o, t, p) => (http.post('/admin/report/getRewardStats', o, t, p))
export const getTaskStats             = (o, t, p) => (http.post('/admin/report/getTaskStats', o, t, p))
export const getStaticsInfo           = (o, t, p) => (http.post('/admin/report/index', o, t, p))
export const exportTable              = (o, t, p) => (http.get('/admin/report/export', o, t, p))
export const getUserProfilePage       = (o, t, p) => (http.post('/admin/report/getUserProfilePage', o, t, p))
export const getUserInfo              = (o, t, p) => (http.post('/admin/user/getUserInfo', o, t, p))
export const downLoadResume           = (o, t, p) => (http.get('/user/downLoadResume', o, t, p))
export const auditUser                = (o, t, p) => (http.post('/admin/user/auditUser', o, t, p))
export const updateUser               = (o, t, p) => (http.post('/admin/user/updateUser', o, t, p))
export const getUserPage              = (o, t, p) => (http.post('/admin/user/getUserPage', o, t, p))
export const getTaskInfo              = (o, t, p) => (http.post('/admin/task/getTaskInfo', o, t, p))
export const updateTask               = (o, t, p) => (http.post('/admin/task/updateTask', o, t, p))
export const uploadTaskIcon           = (o, t, p) => (http.post('/admin/task/uploadTaskIcon', o, t, p))
export const auditEntryFormUser       = (o, t, p) => (http.post('/admin/task/auditEntryFormUser', o, t, p))
export const rewardEntryFromUser      = (o, t, p) => (http.post('/admin/task/rewardEntryFromUser', o, t, p))
export const getEntryFormInfo         = (o, t, p) => (http.post('/admin/task/getEntryFormInfo', o, t, p))
export const getTaskPage              = (o, t, p) => (http.post('/admin/task/getTaskPage', o, t, p))
export const addTask                  = (o, t, p) => (http.post('/admin/task/addTask', o, t, p))

export const statisticUserProfilePage = (o, t, p) => (http.get('/report/getUserProfilePage', o, t, p))
export const getResourcePageAPI       = (o, t, p) => (http.get('/admin/resource/getResourcePage', o, t, p))
export const addResourceAPI           = (o, t, p) => (http.get('/admin/resource/addResource', o, t, p))
export const getRolePageAPI           = (o, t, p) => (http.get('/admin/role/getRolePage', o, t, p))
export const getUserPageAPI           = (o, t, p) => (http.post('/admin/admin/user/getUserPage', o, t, p))
export const getRoleListAPI           = (o, t, p) => (http.post('/admin/unperm/admin/role/getRoleList', o, t, p))
export const addUserAPI               = (o, t, p) => (http.post('/admin/admin/user/addUser', o, t, p))
export const getUserInfoAPI           = (o, t, p) => (http.post('/admin/admin/user/getUserInfo', o, t, p))
export const updateAuthUserAPI        = (o, t, p) => (http.post('/admin/admin/user/updateAuthUser', o, t, p))
export const deleteAuthUserAPI        = (o, t, p) => (http.post('/admin/admin/user/deleteAuthUser', o, t, p))

export const loginApi                 = (o, t, p) => (http.post('/admin/unauth/account/login', o, t, p))
export const TotalPeopleAPI           = (o, t, p) => (http.get('/admin/admin/home/countPartTimeTotalPeople', o, t, p))
export const countComplateTaskAPI     = (o, t, p) => (http.get('/admin/admin/home/countComplateTask', o, t, p))
export const countTotalTaskAPI        = (o, t, p) => (http.get('/admin/admin/home/countTotalTask', o, t, p))

